[package]
name = "jillc"
version = "0.1.0"
edition = "2021"

[dependencies]


[lints.clippy]
pedantic = { level = "warn", priority = -1 }
nursery = { level = "warn", priority = -1 }
unwrap_used = "warn"
module_name_repetitions = "allow"
future_not_send = "allow"
